name: 'External workflow'

on:
  workflow_call:

jobs:
  trigger-terraform-plan:
    name: Test external workflow
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Verify and set build parameters
        run: |
          echo "Test 1"
      - name: Download release
        run: |
          echo "Test 2"